name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # - uses: actions/setup-node@v3
    #   # with:
    #   #   node-version: 16
    # - name: Install dependencies 
    #   run: npm ci
    # - name: Build
    #   run: npm run build
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: '.'
    - name: Configure Pages
      uses: actions/configure-pages@v3
    - name: Deploy
      uses: actions/deploy-pages@v2

    # - uses: JamesIves/github-pages-deploy-action@v4
    #   with:
    #     branch: gh-pages
    #     folder: dist